### ISSUE TITLE
記事投稿フォームのユーザの一番上のユーザで失敗する

### ISSUE THREAD

**Issue by igrs** [ali-inc/dera#13]
何故かuser_idが正しく渡っていない模様です。

**Comment by kaave** [comment]
[誰しもが予想した通り初期化ミスで死んでましたのでとりあえず手直ししました](https://github.com/ali-inc/dera/commit/1a19b57bf7ffe40c1ebbb446108245f48c6ecae2)
ホントはこの辺もきちっと見るべきなんですが、
まーテスト環境を再構築してからのリファクタリングをどっかでやって、その時に、かなと。

**Comment by igrs** [comment]
確認しました。
