### ISSUE TITLE
画像がない場合の記事、ユーザpost時の動作

### ISSUE THREAD

**Issue by igrs** [ali-inc/dera#7]
postパラメータから除外でお願いします。

**Comment by kaave** [comment]
[やっつけときました](https://github.com/ali-inc/dera/commit/8dbb868b39dfca1c86a569a49da93b95e9e67a4b)。

[Postsのほうでなんかエラーでちゃいました](https://github.com/ali-inc/dera/issues/5)が、ログを見てる限りパラメータには問題なさげです。

**Comment by igrs** [comment]
確認しました。変なエラーも消えてます。
