### ISSUE TITLE
UsersAPIで取得できる値がさみしい

### ISSUE THREAD

**Issue by kaave** [ali-inc/dera#8]
/admin/api/users/

`id`しか帰ってこないので、さすがにさみしいです・・・

/admin/users
と同じだけの値がとれたほうが、いいかなーと。

**Comment by igrs** [comment]
[これ](https://github.com/ali-inc/dera/commit/2adfb7f591d0881c6a81d86fbdc567675184dd38)にて解決

**Comment by kaave** [comment]
確認できました :+1:
